### PR TITLE
Add blog post "K-9 Mail is looking for funding"

### PR DESCRIPTION
**Pull request by cketti**

### CODE REVIEW

**Comment by Valodim** [comment]
good call :+1:

it's a slightly steep goal, but then k-9 has a lot of users. If you have not already done so, I would recommend adding a call for action in the app itself as well :)

**Comment by cketti** [comment]
> If you have not already done so, I would recommend adding a call for action in the app itself as well :)

It's on my list. I need to do some reading first to make sure Google doesn't suspend the app.

**Comment by Valodim** [comment]
Ah, good point, that might actually be an issue. I think you should be good fine as long as you don't directly link to (and ideally don't mention) liberapay, but forward people to the website instead.

**Comment by Bubu** [comment]
Sounds pretty good! :-)

**Pull request merged**
