### PR TITLE
Update Bootstrap to improve responsive design

### PR DESCRIPTION
**Pull request by philipwhiuk**
We're currently on an old version of Bootstrap. This moves us to Bootstrap 3 and uses the changes to improve the responsiveness of the layout when on small screen devices.

### CODE REVIEW

**Comment by cketti** [comment]
Looks like this when building locally. Is the "Toggle navigation" thing supposed to be there?

screenshot from 2018-01-19 01-09-31

**Comment by philipwhiuk** [comment]
Is it loading some old CSS from the cache? It looks fine when I serve it locally :(

**Comment by philipwhiuk** [comment]
The 'toggle navigation' is the alt-text for the Bootstrap menu which is shown when on a small screen - e.g. 

screen shot 2018-01-19 at 00 18 13

**Comment by cketti** [comment]
Ah. URLs were pointing to `https://k9mail.github.io` when I built it.

**Comment by cketti** [comment]
Hm. The navigation bar isn't centered for me.

**Comment by philipwhiuk** [comment]
It's not centred particularly amazingly in the live version. As you shrink the screen it jumps about. Then under 980 it breaks horribly.

**Comment by cketti** [comment]
So it's intended to be left aligned now? I didn't expect that. But I don't mind either.

Both `bootstrap.js` and `bootstrap.min.js` seem to be loaded now.
`bootstrap-theme.css` doesn't appear to be used.

Looks good to me otherwise.

**Comment by philipwhiuk** [comment]
Merged in https://github.com/k9mail/k9mail.github.io/commit/a27b0a4fc4c97a24c997ee05e4e9c13d49d76d74

**Pull request closed without merging**
